# -*- coding: utf-8 -*-
"""vuelos DUOC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JaWCgA_ryluzca357lxcQTpmmrWOrIww
"""

import numpy as np
xd= 1
while xd == 1:
  print("1. Seguir\n2. Salir")
  opcion = int(input("Seleccione una opción: "))
  if opcion == 1:
    matriz = np.array([[1,2,3,4,5,6],
                      [7,8,9,10,11,12],
                      [13,14,15,16,17,18],
                      [19,20,21,22,23,24]])
    asiento = int(input("Seleccione el asiento que desee: "))
    resultado = np.where(matriz == asiento)
    x = resultado[0]
    x= str(x)[1:-1]
    print(x) 
    x = int(x)
    y = resultado[1]
    y=str(y)[1:-1]
    print(y)
    y=int(y)
    matriz= matriz.tolist()
    matriz[x][y]="x"
    matriz =np.array(matriz)
    print(matriz)
  else: 
    print("Adios...")
    xd=2